# Generated by Django 6.0.1 on 2026-01-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_publish_post', 'Can publish a post'), ('can_feature_post', 'Can feature a post'), ('can_comments_off', 'Can off the comments')]},
        ),
        migrations.AddField(
            model_name='post',
            name='can_comment',
            field=models.BooleanField(default=True),
        ),
    ]
